# kafka with spark streaming

services:
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "variance:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  spark-jupyter:
    build: ./dockerfiles
    container_name: spark-jupyter
    ports:
      - "8888:8888"
    volumes:
      - notebooks:/home/jovyan/work
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka
      - zookeeper

volumes:
  notebooks: # bind to ./notebooks
    driver: local
    driver_opts:
      type: none
      device: ./notebooks
      o: bind
